[package]
name = "payroll_protocol"
version = "1.0.0"
authors = ["Your Name <you@example.com>"]

[addresses]
# Production/Testnet deployment address (update before deployment)
payroll_protocol = "_"
pyth = "0x7e783b349d3e89cf5931af376ebeadbfab855b3fa239b7ada8f5a92fbea6b387"
deployer = "0xb31e712b26fd295357355f6845e77c888298636609e93bc9b05f0f604049f434"
wormhole = "0x5bc11445584a763c1fa7ed39081f1b920954da14e04b32440cba863d03e19625"

[dev-addresses]
payroll_protocol = "0x5a2fce8cccd5d7d54d631e7c3dec72b36f92e02fc847c331e524c5777e51d400"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "6f83bc6d02207298b2dee91133d75538789bf582", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "6f83bc6d02207298b2dee91133d75538789bf582", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "6f83bc6d02207298b2dee91133d75538789bf582", subdir = "aptos-move/framework/move-stdlib" }
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", rev = "main", subdir = "target_chains/aptos/contracts" }
